---
title: "Figure 2 filtering"
author: "Pierre-Luc Germain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    keep_md: true

---


```{r}
suppressPackageStartupMessages({
  library(ComplexHeatmap)
  library(circlize)
})
suppressMessages(devtools::load_all("../../pipeComp/"))
source("../misc_functions.R")
data(datasets)
```

```{r figure2, fig.width=9, fig.height=4}
res <- readRDS("../data/results_filtering.rds")
co <- res$filtering
co <- co + res$doublet[sapply(strsplit(row.names(res$filtering),";"), FUN=function(x) x[1]),]
co <- abs(as.matrix(co[,grep("^pcOut",colnames(co))]))
ds <- sapply(strsplit(colnames(co),"\\."), FUN=function(x) x[2])
ds <- split(seq_len(ncol(co)), ds)
df <- data.frame(
  method=rep(row.names(co), length(ds)),
  dataset=rep(names(ds), each=nrow(co)),
  maxPCout=unlist(lapply(ds, FUN=function(x) rowMaxs(co[,x]))),
  medianPCout=unlist(lapply(ds, FUN=function(x) rowMedians(co[,x]))),
  meanF1=NA_real_,
  F1atK=NA_real_
)
ds <- sapply(strsplit(colnames(res$clustering)," "), FUN=function(x) x[1])
ds <- split(seq_len(ncol(res$clustering)), ds)
ds$stepElapsed.Koh <- NULL
ds <- lapply(ds, FUN=function(x){
  cl <- res$clustering[,x]
  cl <- cl[grep("seuratvst",row.names(cl),invert=TRUE),]
  by <- sapply(strsplit(row.names(cl),";"), FUN=function(x) paste(x[1:2],collapse=";"))
  meanF1 <- aggregate(cl[[grep("mean_F1",colnames(cl))]], by=list(by), na.rm=TRUE, FUN=mean)
  topF1 <- aggregate(cl[[grep("mean_F1",colnames(cl))]], by=list(by), na.rm=TRUE, FUN=max)
  w <- which(cl[[grep("n_clus",colnames(cl))]]==cl[[grep("nbClusts",colnames(cl))]])
  cl <- cl[w,]
  tmp <- aggregate(cl[[grep("mean_F1",colnames(cl))]], by=list(by[w]), na.rm=TRUE, FUN=mean)
  F1atK <- tmp[,2]
  names(F1atK) <- tmp[,1]
  d <- data.frame(method=meanF1[,1], meanF1=as.numeric(meanF1[,2]), 
                  topF1=as.numeric(topF1[,2]), F1atK=NA_real_)
  d[as.character(tmp[,1]),"F1atK"] <- tmp[,2]
  d
})
ds2 <- bind_rows(ds,.id="dataset")
m <- merge(df, ds2, by=c("dataset","method"))
m$doubletRemoval <- grepl("scDblFinder", m$method)
m$filter <- sapply(strsplit(as.character(m$method),"\\."), FUN=function(x) rev(x)[1])
ag <- aggregate(res$clustering)
df$F1 <- apply(df[,1:2],1,FUN=function(x){
  res$clustering[,grep("")]
  mean()
})

res.f <- readRDS("../../resNew/filtering_endSummary.rds")

res.f$pcCells <- 100-100*res.f$nbCells/datasets[as.character(res.f$dataset),"nbCells"]
res.f$method <- factor(paste(res.f$doubletmethod, res.f$filt))
res.f <- res.f[grep("clust",res.f$method, invert=TRUE),]
levels(res.f$method) <- gsub("nothingFUN ","",levels(res.f$method))

w <- which(abs(res.f$nbClusters-datasets[as.character(res.f$dataset),"subpopulations"])<=1)
#w <- which(res.f$nbClusters==datasets[as.character(res.f$dataset),"subpopulations"])
aris.1 <- cast2(res.f[intersect(w, which(res.f$norm=="norm.seurat")),], formula=method~dataset, value.var="ARI")
aris.2 <- cast2(res.f[intersect(w, which(res.f$norm=="norm.seuratvst")),], formula=method~dataset, value.var="ARI")
pc <- cast2(res.f, formula=method~dataset, value.var="pcCells")
chm(list("ARI (standard norm)"=aris.1, "ARI (sctransform)"=aris.2, "% cells out"=pc), scale=c("column","column","column"), value_format=c("%#.2f","%#.2f","%#.1f"), cluster_columns=FALSE, cluster_rows=FALSE, scaleVar=FALSE)
```



```{r figure2b, fig.width=11, fig.height=4}
HM <- chm(list("ARI"=aris.1, "Total % out"=pc), scale=c("column","column","none"), value_format=c("%#.2f","%#.1f","%#.1f"), cluster_columns=FALSE, cluster_rows=FALSE, scaleVar=FALSE, width=1)

fres <- readRDS("../../resNew/filtering_intermediateSummary.rds")
pc2 <- fres$filtering$pcCell
row.names(pc2) <- reduceMethodNames(row.names(pc2),1:2)
ha <- HeatmapAnnotation(dataset=reduceMethodNames(colnames(pc2),1))
pc2 <- pc2[row.names(aris.1),]
pal <- colorRamp2(c(0,1,5,20,max(pc2)),c("#0000FFFF", "#B38BFFFF", "#FFFFFFFF", "#FF9E81FF", "#FF0000FF"))
HM + Heatmap(pc2, name="% out", bottom_annotation=ha, col=pal, cluster_columns=FALSE, show_column_names=FALSE, width=1, column_title="% per subpopulation")
```


```{r figure2b, fig.width=8.5, fig.height=4}
nb <- fres$filtering$nbCells
pc <- fres$filtering$pcCells
tot <- tot <- 100*pc/nb
row.names(nb) <- row.names(tot) <- row.names(pc) <- reduceMethodNames(row.names(nb),1:2)
subpops <- split(colnames(nb), sapply(strsplit(colnames(nb)," "),FUN=function(x) x[[1]]))
maxOut <- sapply(subpops, FUN=function(x) rowMax(pc[,x]))
maxDeltaPC <- sapply(subpops, FUN=function(x){
  apply(pc[,x],1,FUN=function(x) max(x)-median(x))
})
row.names(maxOut) <- row.names(pc)
# HM + Heatmap(maxDeltaPC[row.names(aris.1),], name="Max % delta", col=pal, cluster_columns=FALSE, show_column_names=FALSE, width=0.5, column_title="Max % difference\nto median")
HM + Heatmap(maxOut[row.names(aris.1),], name="Max %", col=pal, cluster_columns=FALSE, width=1, column_title="Max cluster % out"
```

```{r}
chm(list("ARI"=aris.1, "Total % out"=pc[row.names(aris.1),], "Max cluster % out"=maxOut[row.names(aris.1),]), scale=c("column","column","none"), value_format=c("%#.2f","%#.1f","%#.1f"), cluster_columns=FALSE, cluster_rows=FALSE, scaleVar=FALSE, width=1)
```

```{r, fig.height=3, fig.width=7}
d <- data.frame( celltype=rep(LETTERS[1:3],c(1000,1500,200)), 
                 value=c( rnorm(1000,90,sd=50),
                          rnorm(1500,130,sd=40),
                          rnorm(200,200,sd=40) ) )
library(ggridges)
vl <- function(x) geom_vline(xintercept=x, linetype="dashed")
plot_grid(
  ggplot(d, aes(x=value)) + geom_density(fill="grey") + xlab("value (e.g. log-total-counts)") + vl(35) + vl(205),
  ggplot(d, aes(y=celltype, x=value)) + geom_density_ridges(panel_scaling = FALSE) + xlab("value (e.g. log-total-counts)") + vl(40) + vl(200)
)
```

```{r}
res.f
rf2 <- aggregate(res.f[,c(14:20)], by=res.f[,c(1,2,3,4,13,21)], FUN=mean)
rf2$doublet <- rf2$doubletmethod=="doublet.pl"
ggplot(rf2[which(rf2$norm=="norm.seurat"),], aes(pcCells, ARI, shape=doublet)) + geom_line(mapping=aes(group=resolution), colour="grey") + geom_point(mapping=aes(colour=filt, size=resolution)) + facet_wrap(~dataset, scales="free") + scale_size(range=c(1.5,4)) + scale_x_sqrt() + xlab("% cells excluded")
```

```{r}
load("../../pipComp/data/datasets.RData", verbose=TRUE)
o <- readRDS("../data/filt_allSummaries.rds")
doag <- function(n, prefix="F1"){
  x <- o[[n]]
  x <- x[which(x$norm=="norm.seurat"),]
  x <- x[grep("norm\\.seuratvst|clustFilter", row.names(x), invert=TRUE),]
  x <- x[which(abs(x$nbClusters-datasets[n,"subpopulations"]) <=1),]
  x$pcCells <- round(100*x$nbCells/datasets[n,"nbCells"],2)
  x$method <- ifelse(x$doubletmethod=="doublet.pl", paste("doublet",x$filt), x$filt)
  x <- aggregate(x[,grep(paste0("^",prefix,"\\."),colnames(x))], list(method=x[,"method"]), FUN=mean)
  row.names(x) <- x[,1]
  x[,-1]
}
pr <- do.call(cbind,lapply(names(o), prefix="pr", FUN=doag))
re <- do.call(cbind,lapply(names(o), prefix="re", FUN=doag))
f1 <- do.call(cbind,lapply(names(o), FUN=doag))
ha <- HeatmapAnnotation(dataset=rep(names(o), sapply(o,FUN=function(x) length(grep("^F1\\.",colnames(x))))))
oi <- order(rowSums(f1), decreasing=TRUE)
Heatmap(pr[oi,], cluster_rows=FALSE, bottom_annotation=ha, show_column_names=FALSE, show_heatmap_legend=FALSE, column_title="Precision", show_column_dend=FALSE) +
    Heatmap(re[oi,], cluster_rows = FALSE, bottom_annotation=ha, show_column_names=FALSE, show_heatmap_legend=FALSE, column_title="Recall", show_column_dend=FALSE) + 
    Heatmap(f1[oi,], cluster_rows = FALSE, bottom_annotation=ha, show_column_names=FALSE, name="Score", column_title="F1 score", show_column_dend=FALSE)
```

```{r, fig.width=10, fig.height=14}
cd <- readRDS("../data/cellDists.rds")
lf <- list.files("../datasets", pattern="\\.SCE\\.rds", full.names = TRUE)
names(lf) <- gsub("\\.SCE\\.rds","",basename(lf))
meta <- lapply(lf, FUN=function(x) as.data.frame(colData(readRDS(x))))
cn <- table(unlist(lapply(meta, colnames)))
cn <- names(cn)[which(cn==length(meta))]
meta2 <- lapply(names(meta), FUN=function(x){
  y <- as.data.frame(cd[[x]])
  colnames(y) <- paste("dist",colnames(y))
  x <- meta[[x]]
  n2 <- paste(x$phenoid,row.names(x),sep=".")
  x <- cbind(x[,cn], y[n2,])
  x <- split(x, x$phenoid)
  x <- lapply(x, FUN=function(x){
    x$dist.scaled <- scale(x$`dist seurat`)
    x
  })
  as.data.frame(data.table::rbindlist(x))
})
names(meta2) <- names(meta)
meta2 <- data.table::rbindlist(meta2,idcol="dataset")
# plot_grid(
#   ggplot(meta2, aes(total_counts, total_features_by_counts, colour=dist.scaled)) + geom_point(size=1) + facet_wrap(~dataset, scales = "free") + scale_x_log10() + scale_y_log10(),
#   ggplot(meta2, aes(pct_counts_in_top_50_features, pct_counts_Mt, colour=dist.scaled)) + geom_point() + facet_wrap(~dataset, scales = "free"),
#   nrow = 2, labels=c("A","B")
# )
plot_grid(plotlist=lapply(c("total_counts","total_features_by_counts"), FUN=function(x){
  ggplot(meta2, aes_string(x, 'dist.scaled')) + geom_point() + geom_density_2d() + facet_wrap(~dataset, scales="free") + scale_x_log10()
}), labels=c("A","B"), nrow=2)
plot_grid(plotlist=lapply(c("pct_counts_in_top_50_features","pct_counts_Mt"), FUN=function(x){
  ggplot(meta2, aes_string(x, 'dist.scaled')) + geom_point() + geom_density_2d() + facet_wrap(~dataset, scales="free")
}), labels=c("A","B"), nrow=2)
```