---
title: "SVA - DEA benchmark"
author: "Pierre-Luc Germain"
date: "4/15/2020"
output: html_document
---

## Benchmark datasets



See `data_prep.Rmd` for the data preparation code.


```{r, include=FALSE}
res <- readRDS("aggregated.rds")
```

## Results

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(cowplot)
  library(pipeComp)
  library(grid)
  library(ComplexHeatmap)
})
theme_set(theme_cowplot())
res1b <- res1 <- res
res1$evaluation$dea <- lapply(res1$evaluation$dea, FUN=function(x) x[which(x$k==1),])
res1b$evaluation$dea <- lapply(res1b$evaluation$dea, FUN=function(x){
  x[x$filt=="def.filter" & x$minCount==10,]
})
```

```{r, fig.width=8, fig.height=9.5}
plot_grid(
  grid.grabExpr(draw(
    dea_evalPlot_sig(res1, what=c("logFC.pearson", "logFC.mad", "TPR", "FDR"), agg.by=c("sva.method","dea.method"), row_split="sva.method")
  )),
  plotElapsed(res, agg.by=c("sva.method","dea.method")),
  nrow=2, labels=LETTERS[1:2]
)
```

```{r, fig.width=12, fig.height=7}
plot_grid(
  plot_grid(
    dea_evalPlot_curve(res1, agg.by=c("sva.method","dea.method"), colourBy="dea.method", shapeBy="sva.method") + ggtitle("Using a single surrogate variable"),
    dea_evalPlot_curve(res, agg.by=c("sva.method","k"), colourBy="k", shapeBy="sva.method") + ggtitle("Increasing the number of surrogate variables"),
    nrow=2, labels=LETTERS[1:2]
  ),
  grid.grabExpr(draw(
    dea_evalPlot_sig(res, what=c("logFC.pearson", "TPR", "FDR"), agg.by=c("sva.method","k"), row_split="sva.method", 
                     anno_legend=FALSE, show_column_names=TRUE)
  )),
  nrow=1, rel_widths=c(5,2.5), labels=c(NA,"C")
)
```


```{r, fig.width=12, fig.height=6.5}
plot_grid(
  plot_grid(
    dea_evalPlot_curve(res1, agg.by=c("dea.method","filt","minCount"), colourBy = "dea.method", shapeBy="filter") + ggtitle("DEA methods, Averaging across SVA strategies"),
    dea_evalPlot_curve(res1b, agg.by=c("sva.method")) + ggtitle("SVA methods, averaging across DEA methods"),
    nrow=2, labels=LETTERS[1:2]
  ),
  grid.grabExpr(draw(
    dea_evalPlot_sig(res, what=c("TPR", "FDR"), agg.by=c("sva.method","k"), row_split="sva.method", 
                     anno_legend=FALSE, show_column_names=TRUE)
    )),
  nrow=1, rel_widths=c(5,2), labels=c(NA,"C")
)
```

