---
title: "Supplementary Figures relative to scVI"
author: "Pierre-Luc Germain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r, include=FALSE}
if(!exists('FIG_NB')){
  FIG_NB <- 0
  getFigNb <- function(increment=FALSE){
    if(increment) FIG_NB <<- FIG_NB + 1
    FIG_NB
  }
}

suppressPackageStartupMessages({
  library(ComplexHeatmap)
  library(matrixStats)
  library(pipeComp)
  library(cowplot)
})
source("../misc_functions.R")
```

# Supplementary Figure `r getFigNb(TRUE)`

```{r}
res <- readRDS("../data/scVI.rds")
sil <- res$evaluation$dimreduction$silhouette$top_10_dims
sil$method <- factor(paste(sil$norm, sil$dr))
levels(sil$method) <- c("scVI.LD","scVI+seurat.pca","scVI.LD","sctransform+\nseurat.pca")
levels(sil$dataset) <- c("Koh","Kumar","mixology10x3cl","mixology10x5cl","simMix1","simMix2","Zhengmix4eq","Zhengmix4uneq","Zhengmix8eq")
res$evaluation$dimreduction$silhouette$top_10_dims <- sil
x <- range(res$evaluation$dimreduction$silhouette$top_10_dims$meanSilWidth)
silColBreaks <- unique(round(c(x[1],0,x[2]/2,x[2]),1))
H <- scrna_evalPlot_DR(res, "meanSilWidth", scale=FALSE, agg.by = "method", 
                       reorder_rows=TRUE, value_format="", 
                       show_heatmap_legend=TRUE, anno_legend = TRUE, 
                       heatmap_legend_param=list(at=silColBreaks))

res$evaluation$clustering$method <- factor(paste(res$evaluation$clustering$norm, res$evaluation$clustering$dr))
res$evaluation$clustering$delta.nbClust <- res$evaluation$clustering$n_clus-res$evaluation$clustering$true.nbClusts
levels(res$evaluation$clustering$method) <- c("scVI.LD","scVI+seurat.pca","scVI.LD","sctransform+\nseurat.pca")
H2 <- scrna_evalPlot_clust(res, what="MI", agg.by="method", anno_legend=FALSE) + 
  scrna_evalPlot_clust(res, what="ARI", agg.by="method", anno_legend=FALSE) + 
  scrna_evalPlot_clust(res, what="delta.nbClust", agg.by="method", col=circlize::colorRamp2(c(-6, 0, 6), c("red", "white", "Darkblue")), show_heatmap_legend = FALSE, value_cols = c("black","black"), value_format = "%.0f", anno_legend=FALSE)
```

```{r, fig.width=9, fig.height=3.5}
plot_grid(grid.grabExpr(draw(H)), grid.grabExpr(draw(H2)), ncol=1, labels = LETTERS[1:2])
```

### Supplementary Figure `r getFigNb()`

**scVI evaluation. A:** Average silhouette width per subpopulation using sctransform and standard Seurat PCA, scVI normalization followed by Seurat PCA, or scVI linear decoder (LD). **B:** Clustering accuracy across the same methods followed by Seurat clustering.

\newpage
