---
title: \Large{pipeComp, a general framework for the evaluation of computational pipelines, reveals performant single-cell RNA-seq preprocessing tools}
subtitle: \vspace{0.2cm}\LARGE{Supplementary Figures}\vspace{0.3cm}
author:
- "Pierre-Luc Germain"
- "Anthony Sonrel"
- "Mark D. Robinson"
geometry: margin=1.5cm
output:
  pdf_document:
    toc: true
    fig_width: 8
    fig_height: 6
    citation_package: natbib
bibliography: ../bmc_article.bib
---

\renewcommand{\thepage}{S\arabic{page}}

```{r setup, include=FALSE}
# comment this out to print code
knitr::opts_chunk$set(echo=FALSE)
FIG_NB <- 0
getFigNb <- function(increment=FALSE){
  if(increment) FIG_NB <<- FIG_NB + 1
  FIG_NB
}
```


\newpage

```{r child='supp1b_metrics.Rmd'}
```

```{r child='supp1_dataset_description.Rmd'}
```

```{r child='supp2_filtering.Rmd'}
```

```{r child='supp3_normalization.Rmd'}
```

```{r child='supp4_selection.Rmd'}
```

```{r child='supp5_dr.Rmd'}
```

```{r child='supp6_clust.Rmd'}
```

```{r child='supp_svadea.Rmd'}
```
